In [28]:
import numpy as np

In [77]:
# Sample kmer dict, read from file later
kmers = {
    'ACGATACATAGA': [
        'TAGACGATACATAGAAAAA', 
        'GCCATACGATACATAGATCCTTT', 
        'GGGGACGATACATAGATTG', 
        'CCCCCCACGATACATAGATCGT', 
        'TTACGATACATAGATT'],
}

In [96]:
kmer = list(kmers.keys())[0]
reads = kmers[kmer][:]
locs = []
lens = []
for read in reads:
    locs.append(read.index(kmer))

bases_before = min(locs)
for i in range(len(reads)):
    lens.append(len(reads[i]))
    reads[i] = reads[i][locs[i] - bases_before:]
    
bases_after = min(lens) - len(kmer) - bases_before
for i in range(len(reads)):
    read = reads[i]
    reads[i] = read[0:bases_before] + read[bases_before + len(kmer):bases_before + len(kmer) + bases_after]

for read in reads:
    print(read)

AGAA
ATTC
GGTT
CCTC
TTTT


In [71]:
# Create snp from reads
snp = []
snp_trial = None
for col in range(len(reads[0])):
    snp_col = []
    vals = []
    for read in reads:
        if read[col] not in vals:
            vals.append(read[col])

        snp_col.append(vals.index(read[col]))
    snp_col = np.array(snp_col)
    snp_col.shape = [len(snp_col), 1]
    
    if snp_trial is not None:
        snp_trial = np.concatenate((snp_trial, snp_col), axis=1)
    else:
        snp_trial = snp_col
    
print(snp_trial)

[[0 0 0 0]
 [0 1 0 1]
 [1 0 0 1]
 [2 2 0 1]
 [3 1 1 2]]


In [54]:
arr = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr.shape = [3, 1]
arr2.shape = [3, 1]
arr3.shape = [3, 1]
arr4 = np.concatenate((arr, arr2), axis=1)
arr5 = np.concatenate((arr4, arr3), axis=1)
arr5

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])